feat(haptic): add haptic engine feedback notification support
relevantfruit/Relevant-Informer pull request #7
Opened 2020-07-18 19:10 UTC by anonrig

2020-07-18 19:12 UTC, rufmirza commented on Sources/RelevantInformer/API/RIAttributes+NotificationHapticFeedback.swift
> +
pls delete new line

2020-07-18 19:14 UTC, anonrig commented on Sources/RelevantInformer/API/RIAttributes+NotificationHapticFeedback.swift
> +
👍

2020-07-18 19:24 UTC, cci-rmirza requested changes

2020-07-18 19:24 UTC, rufmirza commented on Sources/RelevantInformer/API/RIAttributes.swift
> +  public var hapticFeedbackType: NotificationHapticFeedback = .none
```suggestion
  public var hapticFeedback: HapticFeedback = .none
```

2020-07-18 19:24 UTC, rufmirza commented on Sources/RelevantInformer/API/RIAttributes+NotificationHapticFeedback.swift
> +  enum NotificationHapticFeedback {
```suggestion
  enum HapticFeedback {
```

2020-07-18 19:24 UTC, rufmirza commented on Sources/RelevantInformer/API/RIAttributes+NotificationHapticFeedback.swift
> +// MARK: - FeedbackTypes
pls delete this MARK

2020-07-18 19:24 UTC, rufmirza commented on Sources/RelevantInformer/API/RIAttributes+NotificationHapticFeedback.swift
> +    }
```
// MARK: - Feedback Generator

extension RIAttributes.HapticFeedback {
  
  func generate() {
    if let style = self.haptic {
      UIImpactFeedbackGenerator(style: style).impactOccurred()
    }
  }
}

```

2020-07-18 19:24 UTC, rufmirza commented on Sources/RelevantInformer/MainComponents/RIRootViewController.swift
> +    attributes.hapticFeedbackType.performIfNeeded()
```suggestion
    attributes.hapticFeedback.generate()
```

2020-07-18 19:24 UTC, rufmirza commented on Sources/RelevantInformer/API/RIAttributes+NotificationHapticFeedback.swift
> +    }
Aslında ben olsam bu kodu komple başka bir extension'a alırdım. Attributes'un bir şey generate edemiyor olması lazım.

2020-07-18 19:24 UTC, rufmirza commented on Sources/RelevantInformer/API/RIAttributes+NotificationHapticFeedback.swift
> +//  RIAttributes+FeedbackStyles.swift
```suggestion
//  RIAttributes+HapticFeedback.swift
```

2020-07-18 19:24 UTC, rufmirza commented on Sources/RelevantInformer/API/RIAttributes+NotificationHapticFeedback.swift
> +//  RIAttributes+FeedbackStyles.swift
Please change the filename as well.

2020-07-19 08:26 UTC, anonrig commented
@rufmirza done and done.

2020-07-19 08:27 UTC, cci-rmirza approved these changes

2020-07-19 09:04 UTC, merged